/**
 * Centralized Auth Error Codes
 * Use these constants instead of hardcoding strings
 */

export const AUTH_ERROR_CODES = {
  // Authentication
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_CHECK_FAILED: 'AUTH_CHECK_FAILED',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',
  TOKEN_REVOCATION_FAILED: 'TOKEN_REVOCATION_FAILED',
  TOKEN_BULK_REVOCATION_FAILED: 'TOKEN_BULK_REVOCATION_FAILED',

  // Account Status
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_LOCKED: 'ACCOUNT_NOT_LOCKED',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_BANNED: 'USER_NOT_BANNED',
  USER_ALREADY_ACTIVE: 'USER_ALREADY_ACTIVE',
  USER_NOT_ORGANIZER: 'USER_NOT_ORGANIZER',

  // Registration
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  INVALID_ROLE: 'INVALID_ROLE',
  INVALID_REGISTRATION_CODE: 'INVALID_REGISTRATION_CODE',

  // Password
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  PASSWORD_COMPROMISED: 'PASSWORD_COMPROMISED',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  PASSWORD_RECENTLY_USED: 'PASSWORD_RECENTLY_USED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  PASSWORD_CHANGE_FAILED: 'PASSWORD_CHANGE_FAILED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  PASSWORD_HASHING_FAILED: 'PASSWORD_HASHING_FAILED',
  PASSWORD_COMPARISON_FAILED: 'PASSWORD_COMPARISON_FAILED',

  // OTP
  INVALID_OTP: 'INVALID_OTP',
  INVALID_CODE: 'INVALID_CODE',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_NOT_FOUND: 'OTP_NOT_FOUND_OR_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS_EXCEEDED',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_GENERATION_FAILED: 'OTP_GENERATION_FAILED',
  OTP_VERIFICATION_FAILED: 'OTP_VERIFICATION_FAILED',
  OTP_INVALIDATION_FAILED: 'OTP_INVALIDATION_FAILED',
  OTP_BULK_INVALIDATION_FAILED: 'OTP_BULK_INVALIDATION_FAILED',
  OTP_CLEANUP_FAILED: 'OTP_CLEANUP_FAILED',
  OTP_STATS_FETCH_FAILED: 'OTP_STATS_FETCH_FAILED',

  // 2FA
  TWO_FA_REQUIRED: '2FA_REQUIRED',
  TWO_FA_SETUP_REQUIRED: '2FA_SETUP_REQUIRED',
  TWO_FA_NOT_ENABLED: '2FA_NOT_ENABLED',
  TWO_FA_NOT_INITIATED: '2FA_NOT_INITIATED',
  TWO_FA_NOT_SETUP: '2FA_NOT_SETUP',
  TWO_FA_INVALID_CODE: 'TWO_FA_INVALID_CODE',
  TWO_FA_SETUP_FAILED: '2FA_SETUP_FAILED',
  TWO_FA_VERIFICATION_FAILED: '2FA_VERIFICATION_FAILED',
  TWO_FA_DISABLE_FAILED: '2FA_DISABLE_FAILED',
  TWO_FA_LOGIN_FAILED: '2FA_LOGIN_FAILED',
  INVALID_BACKUP_CODE: 'INVALID_BACKUP_CODE',
  NO_BACKUP_CODES: 'NO_BACKUP_CODES',
  BACKUP_CODE_VERIFICATION_FAILED: 'BACKUP_CODE_VERIFICATION_FAILED',
  BACKUP_CODES_REGENERATION_FAILED: 'BACKUP_CODES_REGENERATION_FAILED',

  // Email Verification
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',

  // Session
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',
  SESSION_REFRESH_FAILED: 'SESSION_REFRESH_FAILED',
  SESSION_REVOKE_FAILED: 'SESSION_REVOCATION_FAILED',
  SESSION_INFO_FETCH_FAILED: 'SESSION_INFO_FETCH_FAILED',
  LOGOUT_FAILED: 'LOGOUT_ALL_FAILED',

  // Rate Limiting
  RATE_LIMITED: 'RATE_LIMITED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // IP/Security
  IP_BLOCKED: 'IP_BLOCKED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',

  // Admin
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  ADMIN_INACTIVE: 'ADMIN_INACTIVE',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  ADMIN_NOT_SETUP: 'ADMIN_NOT_SETUP',
  ADMIN_NOT_WHITELISTED: 'ADMIN_NOT_WHITELISTED',
  ADMIN_ALREADY_EXISTS: 'ADMIN_ALREADY_EXISTS',
  ADMIN_PASSWORD_TOO_WEAK: 'ADMIN_PASSWORD_TOO_WEAK',
  ADMIN_ROLE_REVOKED: 'ADMIN_ROLE_REVOKED',
  ADMIN_2FA_VERIFICATION_FAILED: 'ADMIN_2FA_VERIFICATION_FAILED',
  ADMIN_2FA_LOGIN_FAILED: 'ADMIN_2FA_LOGIN_FAILED',
  SUPER_ADMIN_REQUIRED: 'SUPER_ADMIN_REQUIRED',
  SELF_ACTION_NOT_ALLOWED: 'SELF_ACTION_NOT_ALLOWED',
  CANNOT_BAN_ADMIN: 'CANNOT_BAN_ADMIN',
  CANNOT_DEACTIVATE_ADMIN: 'CANNOT_DEACTIVATE_ADMIN',
  CANNOT_CHANGE_ADMIN_ROLE: 'CANNOT_CHANGE_ADMIN_ROLE',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_FIELDS: 'MISSING_REQUIRED_FIELDS',

  // Audit
  AUDIT_CLEANUP_FAILED: 'AUDIT_CLEANUP_FAILED',
  AUDIT_SEARCH_FAILED: 'AUDIT_SEARCH_FAILED',
  AUDIT_TRAIL_FETCH_FAILED: 'AUDIT_TRAIL_FETCH_FAILED',
  AUDIT_FETCH_FAILED: 'AUDIT_FETCH_FAILED',

  // Crypto
  HASHING_FAILED: 'HASHING_FAILED',
  HASH_COMPARISON_FAILED: 'HASH_COMPARISON_FAILED',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
  FETCH_FAILED: 'FETCH_FAILED',
  INVALID_FLOW: 'INVALID_FLOW',
  LOGIN_FAILED: 'LOGIN_FAILED',
  // Google Auth Error Codes
  INVALID_GOOGLE_TOKEN: 'INVALID_GOOGLE_TOKEN',
  GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
  GOOGLE_LINK_FAILED: 'GOOGLE_LINK_FAILED',
  GOOGLE_ALREADY_LINKED: 'GOOGLE_ALREADY_LINKED',
  ACCOUNT_EXISTS_LINK_REQUIRED: 'ACCOUNT_EXISTS_LINK_REQUIRED',
  PASSWORD_REQUIRED_FOR_LINK: 'PASSWORD_REQUIRED_FOR_LINK',
  GOOGLE_ONLY_ACCOUNT: 'GOOGLE_ONLY_ACCOUNT',
  LOCAL_AUTH_ALREADY_EXISTS: 'LOCAL_AUTH_ALREADY_EXISTS',
  NO_AUTH_METHOD: 'NO_AUTH_METHOD',
} as const;

export type AuthErrorCode = typeof AUTH_ERROR_CODES[keyof typeof AUTH_ERROR_CODES];

/**
 * HTTP Status codes for common error types
 */
export const ERROR_STATUS_MAP: Record<string, number> = {
  [AUTH_ERROR_CODES.AUTH_REQUIRED]: 401,
  [AUTH_ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [AUTH_ERROR_CODES.INVALID_TOKEN]: 401,
  [AUTH_ERROR_CODES.TOKEN_EXPIRED]: 401,
  [AUTH_ERROR_CODES.TOKEN_REVOKED]: 401,
  [AUTH_ERROR_CODES.MISSING_TOKEN]: 401,
  [AUTH_ERROR_CODES.INVALID_REFRESH_TOKEN]: 401,
  [AUTH_ERROR_CODES.INVALID_CURRENT_PASSWORD]: 401,
  [AUTH_ERROR_CODES.TWO_FA_INVALID_CODE]: 401,
  [AUTH_ERROR_CODES.INVALID_BACKUP_CODE]: 401,
  [AUTH_ERROR_CODES.ACCOUNT_BANNED]: 403,
  [AUTH_ERROR_CODES.ACCOUNT_INACTIVE]: 403,
  [AUTH_ERROR_CODES.EMAIL_NOT_VERIFIED]: 403,
  [AUTH_ERROR_CODES.IP_BLOCKED]: 403,
  [AUTH_ERROR_CODES.ADMIN_REQUIRED]: 403,
  [AUTH_ERROR_CODES.ADMIN_NOT_WHITELISTED]: 403,
  [AUTH_ERROR_CODES.SUPER_ADMIN_REQUIRED]: 403,
  [AUTH_ERROR_CODES.SELF_ACTION_NOT_ALLOWED]: 403,
  [AUTH_ERROR_CODES.CANNOT_BAN_ADMIN]: 403,
  [AUTH_ERROR_CODES.CANNOT_DEACTIVATE_ADMIN]: 403,
  [AUTH_ERROR_CODES.CANNOT_CHANGE_ADMIN_ROLE]: 403,
  [AUTH_ERROR_CODES.USER_NOT_FOUND]: 404,
  [AUTH_ERROR_CODES.ADMIN_NOT_FOUND]: 404,
  [AUTH_ERROR_CODES.SESSION_NOT_FOUND]: 404,
  [AUTH_ERROR_CODES.OTP_NOT_FOUND]: 404,
  [AUTH_ERROR_CODES.ACCOUNT_NOT_FOUND]: 404,
  [AUTH_ERROR_CODES.EMAIL_ALREADY_EXISTS]: 409,
  [AUTH_ERROR_CODES.USERNAME_ALREADY_EXISTS]: 409,
  [AUTH_ERROR_CODES.ADMIN_ALREADY_EXISTS]: 409,
  [AUTH_ERROR_CODES.ACCOUNT_LOCKED]: 423,
  [AUTH_ERROR_CODES.RATE_LIMITED]: 429,
  [AUTH_ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [AUTH_ERROR_CODES.OTP_MAX_ATTEMPTS]: 429,
  [AUTH_ERROR_CODES.INTERNAL_ERROR]: 500,
  [AUTH_ERROR_CODES.ADMIN_2FA_LOGIN_FAILED]: 401,
  [AUTH_ERROR_CODES.ADMIN_2FA_VERIFICATION_FAILED]: 401,
  [AUTH_ERROR_CODES.INVALID_REGISTRATION_CODE]: 401,
  [AUTH_ERROR_CODES.TWO_FA_VERIFICATION_FAILED]: 401,
  [AUTH_ERROR_CODES.TWO_FA_SETUP_FAILED]: 400,
  [AUTH_ERROR_CODES.AUTH_CHECK_FAILED]: 500,
  [AUTH_ERROR_CODES.MISSING_FIELDS]: 400,
  [AUTH_ERROR_CODES.NOT_AUTHENTICATED]: 401,
  [AUTH_ERROR_CODES.INVALID_CODE]: 400,
};

/**
 * Get HTTP status code for an error code
 */
export const getStatusForError = (errorCode: string): number => {
  return ERROR_STATUS_MAP[errorCode] || 400;
};

/**
 * User-friendly error messages for error codes
 */
export const ERROR_MESSAGES: Record<string, string> = {
  [AUTH_ERROR_CODES.AUTH_REQUIRED]: 'Authentication required',
  [AUTH_ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password',
  [AUTH_ERROR_CODES.INVALID_TOKEN]: 'Invalid or malformed token',
  [AUTH_ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [AUTH_ERROR_CODES.TOKEN_REVOKED]: 'Token has been revoked',
  [AUTH_ERROR_CODES.MISSING_TOKEN]: 'Authorization token is missing',
  [AUTH_ERROR_CODES.INVALID_REFRESH_TOKEN]: 'Invalid or expired refresh token',
  [AUTH_ERROR_CODES.ACCOUNT_BANNED]: 'Account has been suspended',
  [AUTH_ERROR_CODES.ACCOUNT_INACTIVE]: 'Account is deactivated',
  [AUTH_ERROR_CODES.ACCOUNT_LOCKED]: 'Account is temporarily locked due to too many failed attempts',
  [AUTH_ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [AUTH_ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'Email is already registered',
  [AUTH_ERROR_CODES.USERNAME_ALREADY_EXISTS]: 'Username is already taken',
  [AUTH_ERROR_CODES.WEAK_PASSWORD]: 'Password does not meet requirements',
  [AUTH_ERROR_CODES.PASSWORD_COMPROMISED]: 'Password has been found in data breaches',
  [AUTH_ERROR_CODES.INVALID_CURRENT_PASSWORD]: 'Current password is incorrect',
  [AUTH_ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Please verify your email before logging in',
  [AUTH_ERROR_CODES.TWO_FA_REQUIRED]: '2FA verification required',
  [AUTH_ERROR_CODES.TWO_FA_INVALID_CODE]: 'Invalid 2FA verification code',
  [AUTH_ERROR_CODES.INVALID_OTP]: 'Invalid or expired verification code',
  [AUTH_ERROR_CODES.OTP_MAX_ATTEMPTS]: 'Too many failed attempts. Please request a new code.',
  [AUTH_ERROR_CODES.RATE_LIMITED]: 'Too many requests. Please try again later.',
  [AUTH_ERROR_CODES.ADMIN_REQUIRED]: 'Admin privileges required',
  [AUTH_ERROR_CODES.ADMIN_NOT_SETUP]: 'Admin account not set up',
  [AUTH_ERROR_CODES.INTERNAL_ERROR]: 'An unexpected error occurred',
  [AUTH_ERROR_CODES.INVALID_REGISTRATION_CODE]: 'Invalid registration code',
  [AUTH_ERROR_CODES.ADMIN_2FA_VERIFICATION_FAILED]: 'Admin 2FA verification failed',
  [AUTH_ERROR_CODES.ADMIN_2FA_LOGIN_FAILED]: 'Admin 2FA login failed',
  [AUTH_ERROR_CODES.TWO_FA_VERIFICATION_FAILED]: '2FA verification failed',
  [AUTH_ERROR_CODES.TWO_FA_SETUP_FAILED]: '2FA setup failed',
  [AUTH_ERROR_CODES.AUTH_CHECK_FAILED]: 'Authentication check failed',
  [AUTH_ERROR_CODES.MISSING_FIELDS]: 'Required fields are missing',
  [AUTH_ERROR_CODES.NOT_AUTHENTICATED]: 'User is not authenticated',
  [AUTH_ERROR_CODES.INVALID_CODE]: 'Invalid code',
};

/**
 * Get user-friendly message for an error code
 */
export const getMessageForError = (errorCode: string): string => {
  return ERROR_MESSAGES[errorCode] || 'An error occurred';
};
