/**
 * Centralized Error Codes
 * Use these constants instead of hardcoding strings
 */

export const ERROR_CODES = {
  // ============================================
  // AUTHENTICATION ERRORS
  // ============================================
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_CHECK_FAILED: 'AUTH_CHECK_FAILED',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',
  TOKEN_REVOCATION_FAILED: 'TOKEN_REVOCATION_FAILED',
  TOKEN_BULK_REVOCATION_FAILED: 'TOKEN_BULK_REVOCATION_FAILED',

  // ============================================
  // ACCOUNT STATUS ERRORS
  // ============================================
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_LOCKED: 'ACCOUNT_NOT_LOCKED',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_BANNED: 'USER_NOT_BANNED',
  USER_ALREADY_ACTIVE: 'USER_ALREADY_ACTIVE',
  USER_NOT_ORGANIZER: 'USER_NOT_ORGANIZER',
  USER_PROFILE_INCOMPLETE: 'USER_PROFILE_INCOMPLETE',

  // ============================================
  // REGISTRATION (AUTH) ERRORS
  // ============================================
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  INVALID_ROLE: 'INVALID_ROLE',
  INVALID_REGISTRATION_CODE: 'INVALID_REGISTRATION_CODE',

  // ============================================
  // PASSWORD ERRORS
  // ============================================
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  PASSWORD_COMPROMISED: 'PASSWORD_COMPROMISED',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  PASSWORD_RECENTLY_USED: 'PASSWORD_RECENTLY_USED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  PASSWORD_CHANGE_FAILED: 'PASSWORD_CHANGE_FAILED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  PASSWORD_HASHING_FAILED: 'PASSWORD_HASHING_FAILED',
  PASSWORD_COMPARISON_FAILED: 'PASSWORD_COMPARISON_FAILED',

  // ============================================
  // OTP ERRORS
  // ============================================
  INVALID_OTP: 'INVALID_OTP',
  INVALID_CODE: 'INVALID_CODE',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_NOT_FOUND: 'OTP_NOT_FOUND_OR_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS_EXCEEDED',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_GENERATION_FAILED: 'OTP_GENERATION_FAILED',
  OTP_VERIFICATION_FAILED: 'OTP_VERIFICATION_FAILED',
  OTP_INVALIDATION_FAILED: 'OTP_INVALIDATION_FAILED',
  OTP_BULK_INVALIDATION_FAILED: 'OTP_BULK_INVALIDATION_FAILED',
  OTP_CLEANUP_FAILED: 'OTP_CLEANUP_FAILED',
  OTP_STATS_FETCH_FAILED: 'OTP_STATS_FETCH_FAILED',

  // ============================================
  // 2FA ERRORS
  // ============================================
  TWO_FA_REQUIRED: '2FA_REQUIRED',
  TWO_FA_SETUP_REQUIRED: '2FA_SETUP_REQUIRED',
  TWO_FA_NOT_ENABLED: '2FA_NOT_ENABLED',
  TWO_FA_NOT_INITIATED: '2FA_NOT_INITIATED',
  TWO_FA_NOT_SETUP: '2FA_NOT_SETUP',
  TWO_FA_INVALID_CODE: 'TWO_FA_INVALID_CODE',
  TWO_FA_SETUP_FAILED: '2FA_SETUP_FAILED',
  TWO_FA_VERIFICATION_FAILED: '2FA_VERIFICATION_FAILED',
  TWO_FA_DISABLE_FAILED: '2FA_DISABLE_FAILED',
  TWO_FA_LOGIN_FAILED: '2FA_LOGIN_FAILED',
  INVALID_BACKUP_CODE: 'INVALID_BACKUP_CODE',
  NO_BACKUP_CODES: 'NO_BACKUP_CODES',
  BACKUP_CODE_VERIFICATION_FAILED: 'BACKUP_CODE_VERIFICATION_FAILED',
  BACKUP_CODES_REGENERATION_FAILED: 'BACKUP_CODES_REGENERATION_FAILED',

  // ============================================
  // EMAIL VERIFICATION ERRORS
  // ============================================
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',

  // ============================================
  // SESSION ERRORS
  // ============================================
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',
  SESSION_REFRESH_FAILED: 'SESSION_REFRESH_FAILED',
  SESSION_REVOKE_FAILED: 'SESSION_REVOCATION_FAILED',
  SESSION_INFO_FETCH_FAILED: 'SESSION_INFO_FETCH_FAILED',
  LOGOUT_FAILED: 'LOGOUT_ALL_FAILED',

  // ============================================
  // RATE LIMITING ERRORS
  // ============================================
  RATE_LIMITED: 'RATE_LIMITED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ============================================
  // IP/SECURITY ERRORS
  // ============================================
  IP_BLOCKED: 'IP_BLOCKED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',

  // ============================================
  // ADMIN ERRORS
  // ============================================
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  ADMIN_INACTIVE: 'ADMIN_INACTIVE',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  ADMIN_NOT_SETUP: 'ADMIN_NOT_SETUP',
  ADMIN_NOT_WHITELISTED: 'ADMIN_NOT_WHITELISTED',
  ADMIN_ALREADY_EXISTS: 'ADMIN_ALREADY_EXISTS',
  ADMIN_PASSWORD_TOO_WEAK: 'ADMIN_PASSWORD_TOO_WEAK',
  ADMIN_ROLE_REVOKED: 'ADMIN_ROLE_REVOKED',
  ADMIN_2FA_VERIFICATION_FAILED: 'ADMIN_2FA_VERIFICATION_FAILED',
  ADMIN_2FA_LOGIN_FAILED: 'ADMIN_2FA_LOGIN_FAILED',
  SUPER_ADMIN_REQUIRED: 'SUPER_ADMIN_REQUIRED',
  SELF_ACTION_NOT_ALLOWED: 'SELF_ACTION_NOT_ALLOWED',
  CANNOT_BAN_ADMIN: 'CANNOT_BAN_ADMIN',
  CANNOT_DEACTIVATE_ADMIN: 'CANNOT_DEACTIVATE_ADMIN',
  CANNOT_CHANGE_ADMIN_ROLE: 'CANNOT_CHANGE_ADMIN_ROLE',

  // ============================================
  // VALIDATION ERRORS
  // ============================================
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_FIELDS: 'MISSING_REQUIRED_FIELDS',

  // ============================================
  // AUDIT ERRORS
  // ============================================
  AUDIT_CLEANUP_FAILED: 'AUDIT_CLEANUP_FAILED',
  AUDIT_SEARCH_FAILED: 'AUDIT_SEARCH_FAILED',
  AUDIT_TRAIL_FETCH_FAILED: 'AUDIT_TRAIL_FETCH_FAILED',
  AUDIT_FETCH_FAILED: 'AUDIT_FETCH_FAILED',

  // ============================================
  // CRYPTO ERRORS
  // ============================================
  HASHING_FAILED: 'HASHING_FAILED',
  HASH_COMPARISON_FAILED: 'HASH_COMPARISON_FAILED',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',

  // ============================================
  // GOOGLE AUTH ERRORS
  // ============================================
  INVALID_GOOGLE_TOKEN: 'INVALID_GOOGLE_TOKEN',
  GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
  GOOGLE_LINK_FAILED: 'GOOGLE_LINK_FAILED',
  GOOGLE_ALREADY_LINKED: 'GOOGLE_ALREADY_LINKED',
  ACCOUNT_EXISTS_LINK_REQUIRED: 'ACCOUNT_EXISTS_LINK_REQUIRED',
  PASSWORD_REQUIRED_FOR_LINK: 'PASSWORD_REQUIRED_FOR_LINK',
  GOOGLE_ONLY_ACCOUNT: 'GOOGLE_ONLY_ACCOUNT',
  LOCAL_AUTH_ALREADY_EXISTS: 'LOCAL_AUTH_ALREADY_EXISTS',
  NO_AUTH_METHOD: 'NO_AUTH_METHOD',

  // ============================================
  // TOURNAMENT ERRORS
  // ============================================
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  TOURNAMENT_FULL: 'TOURNAMENT_FULL',
  TOURNAMENT_CANCELLED: 'TOURNAMENT_CANCELLED',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  STATUS_TRANSITION_FAILED: 'STATUS_TRANSITION_FAILED',
  INVALID_TOURNAMENT_TYPE: 'INVALID_TOURNAMENT_TYPE',
  TOURNAMENT_CREATION_FAILED: 'TOURNAMENT_CREATION_FAILED',
  TOURNAMENT_UPDATE_FAILED: 'TOURNAMENT_UPDATE_FAILED',

  // ============================================
  // TOURNAMENT REGISTRATION ERRORS
  // ============================================
  REGISTRATION_NOT_FOUND: 'REGISTRATION_NOT_FOUND',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  REGISTRATION_NOT_STARTED: 'REGISTRATION_NOT_STARTED',
  REGISTRATION_ENDED: 'REGISTRATION_ENDED',
  REGISTRATION_VALIDATION_FAILED: 'REGISTRATION_VALIDATION_FAILED',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  UNREGISTER_FAILED: 'UNREGISTER_FAILED',

  // ============================================
  // TOURNAMENT CAPACITY ERRORS
  // ============================================
  CAPACITY_TOO_LOW: 'CAPACITY_TOO_LOW',
  INVALID_MIN_PARTICIPANTS: 'INVALID_MIN_PARTICIPANTS',
  CAPACITY_VALIDATION_FAILED: 'CAPACITY_VALIDATION_FAILED',

  // ============================================
  // TOURNAMENT CANCELLATION ERRORS
  // ============================================
  CANCELLATION_WINDOW_CLOSED: 'CANCELLATION_WINDOW_CLOSED',
  CANCELLATION_VALIDATION_FAILED: 'CANCELLATION_VALIDATION_FAILED',

  // ============================================
  // TOURNAMENT UPDATE ERRORS
  // ============================================
  UPDATE_NOT_ALLOWED: 'UPDATE_NOT_ALLOWED',
  UPDATE_VALIDATION_FAILED: 'UPDATE_VALIDATION_FAILED',
  ENTRY_FEE_CHANGE_NOT_ALLOWED: 'ENTRY_FEE_CHANGE_NOT_ALLOWED',

  // ============================================
  // TOURNAMENT PUBLISH/OPEN ERRORS
  // ============================================
  PUBLISH_VALIDATION_FAILED: 'PUBLISH_VALIDATION_FAILED',
  OPEN_VALIDATION_FAILED: 'OPEN_VALIDATION_FAILED',

  // ============================================
  // TOURNAMENT SCHEDULE ERRORS
  // ============================================
  SCHEDULE_INCOMPLETE: 'SCHEDULE_INCOMPLETE',
  SCHEDULE_INVALID_ORDER: 'SCHEDULE_INVALID_ORDER',
  SCHEDULE_PAST: 'SCHEDULE_PAST',
  SCHEDULE_VALIDATION_FAILED: 'SCHEDULE_VALIDATION_FAILED',

  // ============================================
  // TOURNAMENT PRIZE ERRORS
  // ============================================
  PRIZE_DISTRIBUTION_EMPTY: 'PRIZE_DISTRIBUTION_EMPTY',
  PRIZE_DISTRIBUTION_REQUIRED: 'PRIZE_DISTRIBUTION_REQUIRED',
  PRIZE_POSITIONS_DUPLICATE: 'PRIZE_POSITIONS_DUPLICATE',
  PRIZE_POSITIONS_INVALID: 'PRIZE_POSITIONS_INVALID',
  PRIZE_PERCENTAGE_SUM: 'PRIZE_PERCENTAGE_SUM',
  PRIZE_PERCENTAGE_INVALID: 'PRIZE_PERCENTAGE_INVALID',
  PRIZE_DISTRIBUTION_VALIDATION_FAILED: 'PRIZE_DISTRIBUTION_VALIDATION_FAILED',

  // ============================================
  // TOURNAMENT REQUIREMENTS ERRORS
  // ============================================
  AGE_RESTRICTION: 'AGE_RESTRICTION',
  REGION_RESTRICTION: 'REGION_RESTRICTION',
  SKILL_LEVEL_RESTRICTION: 'SKILL_LEVEL_RESTRICTION',
  TEAM_SIZE_NOT_DEFINED: 'TEAM_SIZE_NOT_DEFINED',

  // ============================================
  // GAME PROFILE ERRORS
  // ============================================
  GAME_PROFILE_REQUIRED: 'GAME_PROFILE_REQUIRED',
  INVALID_IN_GAME_ID: 'INVALID_IN_GAME_ID',
  IN_GAME_ID_MISSING: 'IN_GAME_ID_MISSING',
  IN_GAME_ID_INVALID: 'IN_GAME_ID_INVALID',

  // ============================================
  // CHECK-IN ERRORS
  // ============================================
  CHECK_IN_FAILED: 'CHECK_IN_FAILED',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  CHECK_IN_NOT_STARTED: 'CHECK_IN_NOT_STARTED',
  CHECK_IN_ENDED: 'CHECK_IN_ENDED',
  CHECK_IN_WINDOW_NOT_DEFINED: 'CHECK_IN_WINDOW_NOT_DEFINED',
  CHECK_IN_NOT_ENDED: 'CHECK_IN_NOT_ENDED',
  CHECK_IN_STATS_FAILED: 'CHECK_IN_STATS_FAILED',
  CHECK_IN_REMINDER_FAILED: 'CHECK_IN_REMINDER_FAILED',
  CHECK_IN_VALIDATION_FAILED: 'CHECK_IN_VALIDATION_FAILED',
  DISQUALIFY_NO_SHOWS_FAILED: 'DISQUALIFY_NO_SHOWS_FAILED',
  BULK_CHECK_IN_FAILED: 'BULK_CHECK_IN_FAILED',

  // ============================================
  // BRACKET ERRORS
  // ============================================
  BRACKET_GENERATION_FAILED: 'BRACKET_GENERATION_FAILED',
  BRACKET_ALREADY_GENERATED: 'BRACKET_ALREADY_GENERATED',
  BRACKET_NOT_GENERATED: 'BRACKET_NOT_GENERATED',
  BRACKET_GENERATION_VALIDATION_FAILED: 'BRACKET_GENERATION_VALIDATION_FAILED',
  INSUFFICIENT_PARTICIPANTS: 'INSUFFICIENT_PARTICIPANTS',
  WINNER_ADVANCEMENT_FAILED: 'WINNER_ADVANCEMENT_FAILED',

  // ============================================
  // MATCH ERRORS
  // ============================================
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  INVALID_MATCH_STATUS: 'INVALID_MATCH_STATUS',
  MATCH_START_FAILED: 'MATCH_START_FAILED',
  MATCH_NOT_COMPLETED: 'MATCH_NOT_COMPLETED',
  MATCH_ALREADY_COMPLETED: 'MATCH_ALREADY_COMPLETED',
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  NOT_A_PARTICIPANT: 'NOT_A_PARTICIPANT',
  ALREADY_READY: 'ALREADY_READY',
  MARK_READY_FAILED: 'MARK_READY_FAILED',

  // ============================================
  // RESULT SUBMISSION ERRORS
  // ============================================
  RESULT_SUBMISSION_FAILED: 'RESULT_SUBMISSION_FAILED',
  RESULTS_SUBMISSION_FAILED: 'RESULTS_SUBMISSION_FAILED',
  RESULT_ALREADY_SUBMITTED: 'RESULT_ALREADY_SUBMITTED',
  RESULT_CONFIRMATION_FAILED: 'RESULT_CONFIRMATION_FAILED',
  NO_RESULT_SUBMITTED: 'NO_RESULT_SUBMITTED',
  CANNOT_CONFIRM_OWN_RESULT: 'CANNOT_CONFIRM_OWN_RESULT',
  INVALID_RESULT: 'INVALID_RESULT',
  NO_WINNER: 'NO_WINNER',
  NEXT_MATCH_NOT_FOUND: 'NEXT_MATCH_NOT_FOUND',
  WINNER_NOT_FOUND: 'WINNER_NOT_FOUND',
  RESULTS_EMPTY: 'RESULTS_EMPTY',
  DUPLICATE_POSITION: 'DUPLICATE_POSITION',
  INVALID_POSITION: 'INVALID_POSITION',
  RESULTS_NOT_FOUND: 'RESULTS_NOT_FOUND',
  WINNER_VERIFICATION_FAILED: 'WINNER_VERIFICATION_FAILED',
  WINNERS_NOT_VERIFIED: 'WINNERS_NOT_VERIFIED',
  NO_VERIFIED_WINNERS: 'NO_VERIFIED_WINNERS',
  PRIZE_DISTRIBUTION_FAILED: 'PRIZE_DISTRIBUTION_FAILED',

  // ============================================
  // DISPUTE ERRORS
  // ============================================
  DISPUTE_SUBMISSION_FAILED: 'DISPUTE_SUBMISSION_FAILED',
  DISPUTE_RESOLUTION_FAILED: 'DISPUTE_RESOLUTION_FAILED',
  NO_DISPUTE: 'NO_DISPUTE',

  // ============================================
  // FORFEIT ERRORS
  // ============================================
  FORFEIT_FAILED: 'FORFEIT_FAILED',
  OPPONENT_NOT_FOUND: 'OPPONENT_NOT_FOUND',

  // ============================================
  // STATE MACHINE ERRORS
  // ============================================
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  TERMINAL_STATE: 'TERMINAL_STATE',

  // ============================================
  // LOCK ERRORS
  // ============================================
  LOCK_ACQUISITION_FAILED: 'LOCK_ACQUISITION_FAILED',

  // ============================================
  // GAME ERRORS
  // ============================================
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_ALREADY_EXISTS: 'GAME_ALREADY_EXISTS',
  DUPLICATE_SLUG: 'DUPLICATE_SLUG',
  HAS_TOURNAMENTS: 'HAS_TOURNAMENTS',
  TOGGLE_ACTIVE_FAILED: 'TOGGLE_ACTIVE_FAILED',
  UPDATE_STATS_FAILED: 'UPDATE_STATS_FAILED',

  // ============================================
  // GAME REQUEST ERRORS
  // ============================================
  GAME_REQUEST_NOT_FOUND: 'GAME_REQUEST_NOT_FOUND',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  REQUEST_NOT_APPROVED: 'REQUEST_NOT_APPROVED',
  GAME_ALREADY_CREATED: 'GAME_ALREADY_CREATED',
  ADMIN_REVIEW_FAILED: 'ADMIN_REVIEW_FAILED',
  CREATE_GAME_FAILED: 'CREATE_GAME_FAILED',
  MARK_DUPLICATE_FAILED: 'MARK_DUPLICATE_FAILED',
  ALREADY_UPVOTED: 'ALREADY_UPVOTED',
  UPVOTE_FAILED: 'UPVOTE_FAILED',

  // ============================================
  // TEAM ERRORS
  // ============================================
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_FULL: 'TEAM_FULL',
  NOT_TEAM_CAPTAIN: 'NOT_TEAM_CAPTAIN',
  NOT_TEAM_MEMBER: 'NOT_TEAM_MEMBER',
  ALREADY_IN_TEAM: 'ALREADY_IN_TEAM',
  TEAM_CREATION_FAILED: 'TEAM_CREATION_FAILED',

  // ============================================
  // ESCROW ERRORS
  // ============================================
  ESCROW_NOT_FOUND: 'ESCROW_NOT_FOUND',
  ESCROW_CREATION_FAILED: 'ESCROW_CREATION_FAILED',
  ESCROW_DEPOSIT_FAILED: 'ESCROW_DEPOSIT_FAILED',
  ESCROW_RELEASE_FAILED: 'ESCROW_RELEASE_FAILED',

  // ============================================
  // PAYOUT ERRORS
  // ============================================
  PAYOUT_NOT_FOUND: 'PAYOUT_NOT_FOUND',
  PAYOUT_FAILED: 'PAYOUT_FAILED',
  PAYOUT_ALREADY_PROCESSED: 'PAYOUT_ALREADY_PROCESSED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  ORGANIZER_PAYOUT_FAILED: 'ORGANIZER_PAYOUT_FAILED',

  // ============================================
  // NOTIFICATION ERRORS
  // ============================================
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',

  // ============================================
  // GENERIC ERRORS
  // ============================================
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
  FETCH_FAILED: 'FETCH_FAILED',
  INVALID_FLOW: 'INVALID_FLOW',
  LOGIN_FAILED: 'LOGIN_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  UNSUPPORTED_TOURNAMENT_TYPE: 'UNSUPPORTED_TOURNAMENT_TYPE',
  LIST_FAILED: 'LIST_FAILED',
  CREATE_FAILED: 'CREATE_FAILED',
  UPDATE_FAILED: 'UPDATE_FAILED',
  DELETE_FAILED: 'DELETE_FAILED',
} as const;

// Legacy alias for backward compatibility
export const AUTH_ERROR_CODES = ERROR_CODES;
export const TOURNAMENT_ERROR_CODES = ERROR_CODES;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];




export const ERROR_STATUS_MAP: Record<string, number> = {
  // 401 - Unauthorized
  [ERROR_CODES.AUTH_REQUIRED]: 401,
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.INVALID_TOKEN]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.TOKEN_REVOKED]: 401,
  [ERROR_CODES.MISSING_TOKEN]: 401,
  [ERROR_CODES.INVALID_REFRESH_TOKEN]: 401,
  [ERROR_CODES.INVALID_CURRENT_PASSWORD]: 401,
  [ERROR_CODES.TWO_FA_INVALID_CODE]: 401,
  [ERROR_CODES.INVALID_BACKUP_CODE]: 401,
  [ERROR_CODES.ADMIN_2FA_LOGIN_FAILED]: 401,
  [ERROR_CODES.ADMIN_2FA_VERIFICATION_FAILED]: 401,
  [ERROR_CODES.INVALID_REGISTRATION_CODE]: 401,
  [ERROR_CODES.TWO_FA_VERIFICATION_FAILED]: 401,
  [ERROR_CODES.NOT_AUTHENTICATED]: 401,

  // 403 - Forbidden
  [ERROR_CODES.ACCOUNT_BANNED]: 403,
  [ERROR_CODES.ACCOUNT_INACTIVE]: 403,
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 403,
  [ERROR_CODES.IP_BLOCKED]: 403,
  [ERROR_CODES.ADMIN_REQUIRED]: 403,
  [ERROR_CODES.ADMIN_NOT_WHITELISTED]: 403,
  [ERROR_CODES.SUPER_ADMIN_REQUIRED]: 403,
  [ERROR_CODES.SELF_ACTION_NOT_ALLOWED]: 403,
  [ERROR_CODES.CANNOT_BAN_ADMIN]: 403,
  [ERROR_CODES.CANNOT_DEACTIVATE_ADMIN]: 403,
  [ERROR_CODES.CANNOT_CHANGE_ADMIN_ROLE]: 403,
  [ERROR_CODES.TOURNAMENT_FULL]: 403,
  [ERROR_CODES.REGISTRATION_CLOSED]: 403,
  [ERROR_CODES.REGISTRATION_NOT_STARTED]: 403,
  [ERROR_CODES.REGISTRATION_ENDED]: 403,
  [ERROR_CODES.CHECK_IN_NOT_STARTED]: 403,
  [ERROR_CODES.CHECK_IN_ENDED]: 403,
  [ERROR_CODES.CHECK_IN_NOT_ENDED]: 403,
  [ERROR_CODES.NOT_A_PARTICIPANT]: 403,
  [ERROR_CODES.TERMINAL_STATE]: 403,
  [ERROR_CODES.HAS_TOURNAMENTS]: 403,
  [ERROR_CODES.AGE_RESTRICTION]: 403,
  [ERROR_CODES.REGION_RESTRICTION]: 403,
  [ERROR_CODES.SKILL_LEVEL_RESTRICTION]: 403,
  [ERROR_CODES.CANCELLATION_WINDOW_CLOSED]: 403,
  [ERROR_CODES.UPDATE_NOT_ALLOWED]: 403,
  [ERROR_CODES.ENTRY_FEE_CHANGE_NOT_ALLOWED]: 403,
  [ERROR_CODES.NOT_TEAM_CAPTAIN]: 403,
  [ERROR_CODES.NOT_TEAM_MEMBER]: 403,

  // 404 - Not Found
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.ADMIN_NOT_FOUND]: 404,
  [ERROR_CODES.SESSION_NOT_FOUND]: 404,
  [ERROR_CODES.OTP_NOT_FOUND]: 404,
  [ERROR_CODES.ACCOUNT_NOT_FOUND]: 404,
  [ERROR_CODES.TOURNAMENT_NOT_FOUND]: 404,
  [ERROR_CODES.REGISTRATION_NOT_FOUND]: 404,
  [ERROR_CODES.MATCH_NOT_FOUND]: 404,
  [ERROR_CODES.GAME_NOT_FOUND]: 404,
  [ERROR_CODES.GAME_REQUEST_NOT_FOUND]: 404,
  [ERROR_CODES.PARTICIPANT_NOT_FOUND]: 404,
  [ERROR_CODES.NEXT_MATCH_NOT_FOUND]: 404,
  [ERROR_CODES.WINNER_NOT_FOUND]: 404,
  [ERROR_CODES.OPPONENT_NOT_FOUND]: 404,
  [ERROR_CODES.TEAM_NOT_FOUND]: 404,
  [ERROR_CODES.ESCROW_NOT_FOUND]: 404,
  [ERROR_CODES.PAYOUT_NOT_FOUND]: 404,
  [ERROR_CODES.NOTIFICATION_NOT_FOUND]: 404,
  [ERROR_CODES.NOT_FOUND]: 404,

  // 409 - Conflict
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 409,
  [ERROR_CODES.USERNAME_ALREADY_EXISTS]: 409,
  [ERROR_CODES.ADMIN_ALREADY_EXISTS]: 409,
  [ERROR_CODES.ALREADY_REGISTERED]: 409,
  [ERROR_CODES.ALREADY_CHECKED_IN]: 409,
  [ERROR_CODES.BRACKET_ALREADY_GENERATED]: 409,
  [ERROR_CODES.MATCH_ALREADY_COMPLETED]: 409,
  [ERROR_CODES.RESULT_ALREADY_SUBMITTED]: 409,
  [ERROR_CODES.GAME_ALREADY_EXISTS]: 409,
  [ERROR_CODES.DUPLICATE_SLUG]: 409,
  [ERROR_CODES.DUPLICATE_REQUEST]: 409,
  [ERROR_CODES.GAME_ALREADY_CREATED]: 409,
  [ERROR_CODES.ALREADY_UPVOTED]: 409,
  [ERROR_CODES.ALREADY_IN_TEAM]: 409,
  [ERROR_CODES.PAYOUT_ALREADY_PROCESSED]: 409,

  // 400 - Bad Request
  [ERROR_CODES.INVALID_STATUS]: 400,
  [ERROR_CODES.INVALID_STATUS_TRANSITION]: 400,
  [ERROR_CODES.STATUS_TRANSITION_FAILED]: 400,
  [ERROR_CODES.INVALID_TOURNAMENT_TYPE]: 400,
  [ERROR_CODES.INVALID_MATCH_STATUS]: 400,
  [ERROR_CODES.INVALID_IN_GAME_ID]: 400,
  [ERROR_CODES.IN_GAME_ID_INVALID]: 400,
  [ERROR_CODES.INVALID_RESULT]: 400,
  [ERROR_CODES.INVALID_TRANSITION]: 400,
  [ERROR_CODES.CHECK_IN_WINDOW_NOT_DEFINED]: 400,
  [ERROR_CODES.CANNOT_CONFIRM_OWN_RESULT]: 400,
  [ERROR_CODES.NO_WINNER]: 400,
  [ERROR_CODES.TWO_FA_SETUP_FAILED]: 400,
  [ERROR_CODES.MISSING_FIELDS]: 400,
  [ERROR_CODES.INVALID_CODE]: 400,
  [ERROR_CODES.SCHEDULE_INCOMPLETE]: 400,
  [ERROR_CODES.SCHEDULE_INVALID_ORDER]: 400,
  [ERROR_CODES.SCHEDULE_PAST]: 400,
  [ERROR_CODES.PRIZE_DISTRIBUTION_EMPTY]: 400,
  [ERROR_CODES.PRIZE_POSITIONS_DUPLICATE]: 400,
  [ERROR_CODES.PRIZE_POSITIONS_INVALID]: 400,
  [ERROR_CODES.PRIZE_PERCENTAGE_SUM]: 400,
  [ERROR_CODES.PRIZE_PERCENTAGE_INVALID]: 400,
  [ERROR_CODES.CAPACITY_TOO_LOW]: 400,
  [ERROR_CODES.CAPACITY_VALIDATION_FAILED]: 400,
  [ERROR_CODES.INVALID_MIN_PARTICIPANTS]: 400,
  [ERROR_CODES.TEAM_SIZE_NOT_DEFINED]: 400,
  [ERROR_CODES.USER_PROFILE_INCOMPLETE]: 400,

  // 402 - Payment Required
  [ERROR_CODES.PAYMENT_REQUIRED]: 402,
  [ERROR_CODES.INSUFFICIENT_BALANCE]: 402,

  // 410 - Gone
  [ERROR_CODES.TOURNAMENT_CANCELLED]: 410,

  // 412 - Precondition Failed
  [ERROR_CODES.GAME_PROFILE_REQUIRED]: 412,
  [ERROR_CODES.BRACKET_NOT_GENERATED]: 412,
  [ERROR_CODES.MATCH_NOT_COMPLETED]: 412,
  [ERROR_CODES.INSUFFICIENT_PARTICIPANTS]: 412,
  [ERROR_CODES.NO_RESULT_SUBMITTED]: 412,
  [ERROR_CODES.NO_DISPUTE]: 412,
  [ERROR_CODES.REQUEST_NOT_APPROVED]: 412,
  [ERROR_CODES.IN_GAME_ID_MISSING]: 412,
  [ERROR_CODES.PRIZE_DISTRIBUTION_REQUIRED]: 412,

  // 423 - Locked
  [ERROR_CODES.ACCOUNT_LOCKED]: 423,
  [ERROR_CODES.LOCK_ACQUISITION_FAILED]: 423,

  // 429 - Too Many Requests
  [ERROR_CODES.RATE_LIMITED]: 429,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.OTP_MAX_ATTEMPTS]: 429,

  // 500 - Internal Server Error
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.AUTH_CHECK_FAILED]: 500,
  [ERROR_CODES.REGISTRATION_FAILED]: 500,
  [ERROR_CODES.PAYMENT_FAILED]: 500,
  [ERROR_CODES.UNREGISTER_FAILED]: 500,
  [ERROR_CODES.CHECK_IN_FAILED]: 500,
  [ERROR_CODES.CHECK_IN_STATS_FAILED]: 500,
  [ERROR_CODES.CHECK_IN_REMINDER_FAILED]: 500,
  [ERROR_CODES.DISQUALIFY_NO_SHOWS_FAILED]: 500,
  [ERROR_CODES.BULK_CHECK_IN_FAILED]: 500,
  [ERROR_CODES.BRACKET_GENERATION_FAILED]: 500,
  [ERROR_CODES.WINNER_ADVANCEMENT_FAILED]: 500,
  [ERROR_CODES.MATCH_START_FAILED]: 500,
  [ERROR_CODES.MARK_READY_FAILED]: 500,
  [ERROR_CODES.RESULT_SUBMISSION_FAILED]: 500,
  [ERROR_CODES.RESULT_CONFIRMATION_FAILED]: 500,
  [ERROR_CODES.DISPUTE_SUBMISSION_FAILED]: 500,
  [ERROR_CODES.DISPUTE_RESOLUTION_FAILED]: 500,
  [ERROR_CODES.FORFEIT_FAILED]: 500,
  [ERROR_CODES.LIST_FAILED]: 500,
  [ERROR_CODES.FETCH_FAILED]: 500,
  [ERROR_CODES.CREATE_FAILED]: 500,
  [ERROR_CODES.UPDATE_FAILED]: 500,
  [ERROR_CODES.DELETE_FAILED]: 500,
  [ERROR_CODES.TOGGLE_ACTIVE_FAILED]: 500,
  [ERROR_CODES.UPDATE_STATS_FAILED]: 500,
  [ERROR_CODES.ADMIN_REVIEW_FAILED]: 500,
  [ERROR_CODES.CREATE_GAME_FAILED]: 500,
  [ERROR_CODES.MARK_DUPLICATE_FAILED]: 500,
  [ERROR_CODES.UPVOTE_FAILED]: 500,
  [ERROR_CODES.REGISTRATION_VALIDATION_FAILED]: 500,
  [ERROR_CODES.CANCELLATION_VALIDATION_FAILED]: 500,
  [ERROR_CODES.UPDATE_VALIDATION_FAILED]: 500,
  [ERROR_CODES.CHECK_IN_VALIDATION_FAILED]: 500,
  [ERROR_CODES.BRACKET_GENERATION_VALIDATION_FAILED]: 500,
  [ERROR_CODES.PRIZE_DISTRIBUTION_VALIDATION_FAILED]: 500,
  [ERROR_CODES.SCHEDULE_VALIDATION_FAILED]: 500,
  [ERROR_CODES.PUBLISH_VALIDATION_FAILED]: 500,
  [ERROR_CODES.OPEN_VALIDATION_FAILED]: 500,
  [ERROR_CODES.TOURNAMENT_CREATION_FAILED]: 500,
  [ERROR_CODES.TOURNAMENT_UPDATE_FAILED]: 500,
  [ERROR_CODES.TEAM_CREATION_FAILED]: 500,
  [ERROR_CODES.ESCROW_CREATION_FAILED]: 500,
  [ERROR_CODES.ESCROW_DEPOSIT_FAILED]: 500,
  [ERROR_CODES.ESCROW_RELEASE_FAILED]: 500,
  [ERROR_CODES.PAYOUT_FAILED]: 500,
  [ERROR_CODES.NOTIFICATION_SEND_FAILED]: 500,

  // 501 - Not Implemented
  [ERROR_CODES.NOT_IMPLEMENTED]: 501,
  [ERROR_CODES.UNSUPPORTED_TOURNAMENT_TYPE]: 501,
};

/**
 * Get HTTP status code for an error code
 */
export const getStatusForError = (errorCode: string): number => {
  return ERROR_STATUS_MAP[errorCode] || 400;
};

/**
 * User-friendly error messages for error codes
 */
export const ERROR_MESSAGES: Record<string, string> = {
  // Auth messages
  [ERROR_CODES.AUTH_REQUIRED]: 'Authentication required',
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.INVALID_TOKEN]: 'Invalid or malformed token',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.TOKEN_REVOKED]: 'Token has been revoked',
  [ERROR_CODES.MISSING_TOKEN]: 'Authorization token is missing',
  [ERROR_CODES.INVALID_REFRESH_TOKEN]: 'Invalid or expired refresh token',
  [ERROR_CODES.ACCOUNT_BANNED]: 'Account has been suspended',
  [ERROR_CODES.ACCOUNT_INACTIVE]: 'Account is deactivated',
  [ERROR_CODES.ACCOUNT_LOCKED]: 'Account is temporarily locked due to too many failed attempts',
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'Email is already registered',
  [ERROR_CODES.USERNAME_ALREADY_EXISTS]: 'Username is already taken',
  [ERROR_CODES.WEAK_PASSWORD]: 'Password does not meet requirements',
  [ERROR_CODES.PASSWORD_COMPROMISED]: 'Password has been found in data breaches',
  [ERROR_CODES.INVALID_CURRENT_PASSWORD]: 'Current password is incorrect',
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Please verify your email before logging in',
  [ERROR_CODES.TWO_FA_REQUIRED]: '2FA verification required',
  [ERROR_CODES.TWO_FA_INVALID_CODE]: 'Invalid 2FA verification code',
  [ERROR_CODES.INVALID_OTP]: 'Invalid or expired verification code',
  [ERROR_CODES.OTP_MAX_ATTEMPTS]: 'Too many failed attempts. Please request a new code.',
  [ERROR_CODES.RATE_LIMITED]: 'Too many requests. Please try again later.',
  [ERROR_CODES.ADMIN_REQUIRED]: 'Admin privileges required',
  [ERROR_CODES.ADMIN_NOT_SETUP]: 'Admin account not set up',
  [ERROR_CODES.INTERNAL_ERROR]: 'An unexpected error occurred',
  [ERROR_CODES.INVALID_REGISTRATION_CODE]: 'Invalid registration code',
  [ERROR_CODES.ADMIN_2FA_VERIFICATION_FAILED]: 'Admin 2FA verification failed',
  [ERROR_CODES.ADMIN_2FA_LOGIN_FAILED]: 'Admin 2FA login failed',
  [ERROR_CODES.TWO_FA_VERIFICATION_FAILED]: '2FA verification failed',
  [ERROR_CODES.TWO_FA_SETUP_FAILED]: '2FA setup failed',
  [ERROR_CODES.AUTH_CHECK_FAILED]: 'Authentication check failed',
  [ERROR_CODES.MISSING_FIELDS]: 'Required fields are missing',
  [ERROR_CODES.NOT_AUTHENTICATED]: 'User is not authenticated',
  [ERROR_CODES.INVALID_CODE]: 'Invalid code',

  // Tournament messages
  [ERROR_CODES.TOURNAMENT_NOT_FOUND]: 'Tournament not found',
  [ERROR_CODES.TOURNAMENT_FULL]: 'Tournament is full',
  [ERROR_CODES.TOURNAMENT_CANCELLED]: 'Tournament has been cancelled',
  [ERROR_CODES.INVALID_STATUS]: 'Invalid tournament status',
  [ERROR_CODES.INVALID_STATUS_TRANSITION]: 'Invalid Status Transition',
  [ERROR_CODES.STATUS_TRANSITION_FAILED]: 'STATUS_TRANSITION_FAILED',
  [ERROR_CODES.INVALID_TOURNAMENT_TYPE]: 'Invalid tournament type',

  // Registration messages
  [ERROR_CODES.REGISTRATION_NOT_FOUND]: 'Registration not found',
  [ERROR_CODES.REGISTRATION_FAILED]: 'Registration failed',
  [ERROR_CODES.ALREADY_REGISTERED]: 'You are already registered for this tournament',
  [ERROR_CODES.REGISTRATION_CLOSED]: 'Registration is closed',
  [ERROR_CODES.REGISTRATION_NOT_STARTED]: 'Registration has not started yet',
  [ERROR_CODES.REGISTRATION_ENDED]: 'Registration window has ended',
  [ERROR_CODES.PAYMENT_REQUIRED]: 'Payment is required',
  [ERROR_CODES.PAYMENT_FAILED]: 'Payment processing failed',
  [ERROR_CODES.UNREGISTER_FAILED]: 'Failed to unregister',

  // Game profile messages
  [ERROR_CODES.GAME_PROFILE_REQUIRED]: 'Game profile is required',
  [ERROR_CODES.INVALID_IN_GAME_ID]: 'Invalid in-game ID',
  [ERROR_CODES.IN_GAME_ID_MISSING]: 'In-game ID is not set in your profile',
  [ERROR_CODES.IN_GAME_ID_INVALID]: 'In-game ID format is invalid',
  [ERROR_CODES.USER_PROFILE_INCOMPLETE]: 'User profile is incomplete',

  // Check-in messages
  [ERROR_CODES.CHECK_IN_FAILED]: 'Check-in failed',
  [ERROR_CODES.ALREADY_CHECKED_IN]: 'You have already checked in',
  [ERROR_CODES.CHECK_IN_NOT_STARTED]: 'Check-in has not started yet',
  [ERROR_CODES.CHECK_IN_ENDED]: 'Check-in window has ended',
  [ERROR_CODES.CHECK_IN_WINDOW_NOT_DEFINED]: 'Check-in window is not defined',

  // Bracket messages
  [ERROR_CODES.BRACKET_GENERATION_FAILED]: 'Failed to generate bracket',
  [ERROR_CODES.BRACKET_ALREADY_GENERATED]: 'Bracket has already been generated',
  [ERROR_CODES.BRACKET_NOT_GENERATED]: 'Bracket has not been generated yet',
  [ERROR_CODES.INSUFFICIENT_PARTICIPANTS]: 'Not enough participants',

  // Match messages
  [ERROR_CODES.MATCH_NOT_FOUND]: 'Match not found',
  [ERROR_CODES.INVALID_MATCH_STATUS]: 'Invalid match status',
  [ERROR_CODES.MATCH_START_FAILED]: 'Failed to start match',
  [ERROR_CODES.MATCH_NOT_COMPLETED]: 'Match is not completed yet',
  [ERROR_CODES.MATCH_ALREADY_COMPLETED]: 'Match is already completed',
  [ERROR_CODES.PARTICIPANT_NOT_FOUND]: 'Participant not found',
  [ERROR_CODES.NOT_A_PARTICIPANT]: 'You are not a participant in this match',
  [ERROR_CODES.ALREADY_READY]: 'You have already marked yourself as ready',

  // Results messages
  [ERROR_CODES.RESULT_SUBMISSION_FAILED]: 'Failed to submit result',
  [ERROR_CODES.RESULTS_SUBMISSION_FAILED]: 'Results submission failed',
  [ERROR_CODES.RESULT_ALREADY_SUBMITTED]: 'Result has already been submitted',
  [ERROR_CODES.NO_RESULT_SUBMITTED]: 'No result has been submitted yet',
  [ERROR_CODES.CANNOT_CONFIRM_OWN_RESULT]: 'You cannot confirm your own result',
  [ERROR_CODES.INVALID_RESULT]: 'Invalid result data',
  [ERROR_CODES.RESULTS_EMPTY]: 'Winners data cannot be empty',
  [ERROR_CODES.DUPLICATE_POSITION]: 'Duplicate positions are not allowed',
  [ERROR_CODES.INVALID_POSITION]: 'Positions must be positive integers',
  [ERROR_CODES.RESULTS_NOT_FOUND]: 'No results found to verify',
  [ERROR_CODES.WINNER_VERIFICATION_FAILED]: 'Winner verification failed',
  [ERROR_CODES.WINNERS_NOT_VERIFIED]: 'Winners are not verified',
  [ERROR_CODES.NO_VERIFIED_WINNERS]: 'No verified winners to distribute prizes to',
  [ERROR_CODES.PRIZE_DISTRIBUTION_FAILED]: 'Prize distribution failed',

  // State machine messages
  [ERROR_CODES.INVALID_TRANSITION]: 'Invalid status transition',

  // Lock messages
  [ERROR_CODES.LOCK_ACQUISITION_FAILED]: 'Operation is busy, please try again',

  // Schedule messages
  [ERROR_CODES.SCHEDULE_INCOMPLETE]: 'Schedule is incomplete',
  [ERROR_CODES.SCHEDULE_INVALID_ORDER]: 'Schedule dates are not in valid order',
  [ERROR_CODES.SCHEDULE_PAST]: 'Schedule dates cannot be in the past',

  // Prize messages
  [ERROR_CODES.PRIZE_DISTRIBUTION_EMPTY]: 'Prize distribution cannot be empty',
  [ERROR_CODES.PRIZE_DISTRIBUTION_REQUIRED]: 'Prize distribution must be defined',
  [ERROR_CODES.PRIZE_POSITIONS_DUPLICATE]: 'Prize positions must be unique',
  [ERROR_CODES.PRIZE_POSITIONS_INVALID]: 'Prize positions must be positive integers',
  [ERROR_CODES.PRIZE_PERCENTAGE_SUM]: 'Prize percentages must sum to 100%',
  [ERROR_CODES.PRIZE_PERCENTAGE_INVALID]: 'Prize percentages must be between 0 and 100',

  // Restriction messages
  [ERROR_CODES.AGE_RESTRICTION]: 'You do not meet the age requirements',
  [ERROR_CODES.REGION_RESTRICTION]: 'Your region is not allowed for this tournament',
  [ERROR_CODES.SKILL_LEVEL_RESTRICTION]: 'Your skill level does not meet tournament requirements',

  // Cancellation messages
  [ERROR_CODES.CANCELLATION_WINDOW_CLOSED]: 'Cancellation window has closed',

  // Update messages
  [ERROR_CODES.UPDATE_NOT_ALLOWED]: 'Update not allowed in current status',
  [ERROR_CODES.ENTRY_FEE_CHANGE_NOT_ALLOWED]: 'Entry fee cannot be changed',
  [ERROR_CODES.CAPACITY_TOO_LOW]: 'Cannot reduce capacity below current registrations',
  [ERROR_CODES.CAPACITY_VALIDATION_FAILED]: 'Capacity Validation Failed',

  // Generic messages
  [ERROR_CODES.NOT_IMPLEMENTED]: 'Feature not yet implemented',
  [ERROR_CODES.UNSUPPORTED_TOURNAMENT_TYPE]: 'Tournament type not supported',

  // Game messages
  [ERROR_CODES.GAME_NOT_FOUND]: 'Game not found',
  [ERROR_CODES.GAME_ALREADY_EXISTS]: 'Game already exists',
  [ERROR_CODES.DUPLICATE_SLUG]: 'A game with this name already exists',

  // Team messages
  [ERROR_CODES.TEAM_NOT_FOUND]: 'Team not found',
  [ERROR_CODES.TEAM_FULL]: 'Team is full',
  [ERROR_CODES.NOT_TEAM_CAPTAIN]: 'Only the team captain can perform this action',
  [ERROR_CODES.ALREADY_IN_TEAM]: 'You are already in a team for this game',

  // Payout messages
  [ERROR_CODES.INSUFFICIENT_BALANCE]: 'Insufficient balance',
  [ERROR_CODES.PAYOUT_ALREADY_PROCESSED]: 'Payout has already been processed',
  [ERROR_CODES.ORGANIZER_PAYOUT_FAILED]: 'Organizer payout failed',
};

/**
 * Get user-friendly message for an error code
 */
export const getMessageForError = (errorCode: string): string => {
  return ERROR_MESSAGES[errorCode] || 'An error occurred';
};
